### ISSUE TITLE
Typo in instructions

### ISSUE THREAD

**Issue by bortzmeyer** [Tesseract22/zig-ray#1]
` zig-out/bin/raytracer redchair.txt `

It is actually `raytrace` .

(Otherwise, 25 minutes on my desktop PC)

**Comment by Tesseract22** [comment]
Thanks for letting me know. I have fixed the typo.

Would you mind sharing you PC setup?

**Comment by bortzmeyer** [comment]
> Would you mind sharing you PC setup?

AMD Ryzen 5 1600 Six-Core Processor, 1.5 Ghz. 6399.12 bogomips.

8 GB memory.

Ubuntu 22.04 with Linux kernel 6.2.0

**Comment by Tesseract22** [comment]
I am testing on AMD Ryzen 7 4800HS with 8 cores, 2.90 GHz, 16.0 GB RAM. So perhaps that is reasonable? It takes 3 min on single thread and 1 min on 8 threads. You can provide the number of threads like so: `zig-out/bin/raytrace redchair.txt <thread_count>`

**Comment by bortzmeyer** [comment]
Indeed, with 6 threads, only 7 minutes.
